### ISSUE TITLE
App stuck in exception and crashes

### ISSUE THREAD

**Issue by aumtuhin** [FinanzRitter/nativescript-sentry#7]
System.err: StackTrace:
System.err: Zone.runGuarded(file: src/webpack:/guidely/node_modules/@nativescript/zone-js/zone-nativescript.js:155:0)
System.err:     at (file: src/webpack:/guidely/node_modules/@nativescript/zone-js/zone-nativescript.js:129:0)
System.err:     at run(file: src/webpack:/guidely/node_modules/@nativescript/core/timer/index.android.js:22:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)

**Comment by aumtuhin** [comment]
no longer needed
